name: ToMap
version: '1.2'
main: io.github.AvacadoWizard120.toMap.ToMap
api-version: '1.21'
load: STARTUP
authors: [ AvacadoWizard120 ]
website: https://youtube.com/@ConfusingFool93
commands:
  tomap:
    description: Load an image onto a Minecraft map
    usage: /<command> <url> [resize] [width] [height]
permissions:
  tomap.use:
    description: Allows players to use the /tomap command
    default: true